set serveroutput on
set feed off
set COLSEP |
set lines 180

begin
  dbms_output.enable(65536);

  dbms_output.put(chr(10));
  dbms_output.put_line('Arquivo                             Descricao');
  dbms_output.put_line('-------------------------------     -----------------------------------------------------------------------------------');
  dbms_output.put_line('commands                            Exibe descricao dos scrips.');
  dbms_output.put_line('12c_cdb_resource_plans              Displays CDB resource plans.');
  dbms_output.put_line('12c_cdb_resource_plan_directives    Displays CDB resource plan directives.');
  dbms_output.put_line('12c_cdb_resource_profile_directives Displays CDB resource profile directives.');
  dbms_output.put_line('12c_credentials                     Displays information about credentials.');
  dbms_output.put_line('12c_db_size                         Database sizes (For Oracle Database 12c). Used and allocated.It must be run as SYSDBA');
  dbms_output.put_line('12c_services                        Displays information about database services.');
  dbms_output.put_line('archive_area_usage_01               It checks the space used in the Flash Recovery Area.');
  dbms_output.put_line('archive_area_usage_02               It checks what is consuming space in the Flash Recovery Area.');
  dbms_output.put_line('archive_area_usage_03               It shows information about Flashback options and space usage.');
  dbms_output.put_line('archives_generated_last_days        Script to check archives generated for the last days.');
  dbms_output.put_line('archives_generated_last_7_days      Script to check archives generated per hour for last 7 days.');
  dbms_output.put_line('archives_generated_last_15_days     Script to check archives generated per hour for last 15 days.');
  dbms_output.put_line('archives_generated_last_30_days     Archives gerados nos ultimos 30 dias.');
  dbms_output.put_line('archives_information                Archives gerados por dia ate agora.');
  dbms_output.put_line('asm_alias                           Summary report of all alias definitions contained within all ASM disk groups.');
  dbms_output.put_line('asm_clients                         Summary report of all alias definitions contained within all ASM disk groups.');
  dbms_output.put_line('asm_disks_status_01                 Verifying ASM Disks.');
  dbms_output.put_line('asm_disks_status_02                 Verifying ASM Disks with graph information.');
  dbms_output.put_line('asm_drop_files                      Creates a SQL script that removes all ASM files. IMPORTANT: read it before.');
  dbms_output.put_line('asm_files                           Summary report of all files (and file metadata) information for all ASM disk groups.');
  dbms_output.put_line('asm_usage                           Verifying ASM usage.');
  dbms_output.put_line('asmm_components                     Summary report of all dynamic components as part of Oracle ASMM configuration.');
  dbms_output.put_line('awr_reports                         Generates a AWR Report for a specific range of days (Must be as sysdba).');
  dbms_output.put_line('awr_snapshots_dbtime                List of all AWR snapshots and the total database time consumed within its interval.');
  dbms_output.put_line('db_audit_fga                        Database Fine Grained Auditing information (only if auditing is enabled).');
  dbms_output.put_line('db_audit_information                Database auditing information (only if auditing is enabled).');
  dbms_output.put_line('db_audit_standard                   Database Standard Auditing information (only if auditing is enabled).');
  dbms_output.put_line('db_basic_checklist                  Verifying instance status.');
  dbms_output.put_line('db_blocks_corrupted                 Verifying corrupted blocks in the database.');
  dbms_output.put_line('db_blocks_corrupted_objects         Verifying objects into corrupted blocks in the database.');
  dbms_output.put_line('db_blocks_corrupted_objects_size    Verifying objects sizes into corrupted blocks in the database.');
  dbms_output.put_line('db_cache_advice                     Predicts how changes to the buffer cache will affect physical reads.');
  dbms_output.put_line('db_character_set_info               Database character set information.');
  dbms_output.put_line('db_compare_schemas                  Script to compare two Oracle schemas. IMPORTANT: read it before using.');
  dbms_output.put_line('db_compile_all_invalid_objects      Copilando todos os objetos invalidos no BD (conectado como sysdba).');
  dbms_output.put_line('db_compile_all_invalid_objects_01   Script para compilar todos os objetos invalidos.');
  dbms_output.put_line('db_compile_invalid_objects          Listing invalid objects in the db.');
  dbms_output.put_line('db_compress_information             Find out tables with correct datafiles to compress and scripting for execution.');
  dbms_output.put_line('db_controlfiles                     Displays informations about all the database controlfiles.');
  dbms_output.put_line('db_corrupt_segments                 It will map each block from v$database_block_corruption.');
  dbms_output.put_line('db_creation_info                    Show information about database open mode and creation time.');
  dbms_output.put_line('db_create_public_synonym            Criando Sinonimos Publicos para objetos de determinados usuarios.');
  dbms_output.put_line('db_create_space_used_summary        Save summary of database space history over time (read it before applying).');
  dbms_output.put_line('db_db_links                         Verificacao de DB_LINKS da base de dados.');
  dbms_output.put_line('db_db_links_creation                Verificar os DBLinks da base gerando script para criacao dos mesmos em outra base.');
  dbms_output.put_line('db_db_links_usage                   This script will show the user and session associated with using a database link.');
  dbms_output.put_line('db_details_for_unix_pid             Lookup database details for a given Unix process id.');
  dbms_output.put_line('db_disable_pk                       Desabilitando PKs.');
  dbms_output.put_line('db_drop_objects                     Dropar os objetos de um determinado owner.');
  dbms_output.put_line('db_dispatchers                      Displays dispatcher statistics.');
  dbms_output.put_line('db_end_backup                       Verificar as tbs que estao em BEGIN BKP e montar o SQLs para altera-las.');
  dbms_output.put_line('db_execution_plan                   Displays tree-style execution plan of specified statement after it is been explained.');
  dbms_output.put_line('db_extents                          Verifying Tables and Indexes nearing MAX_EXTENTS.');
  dbms_output.put_line('db_features_information             Displays information about used database features.');
  dbms_output.put_line('db_fdb_redo_time_matrix             Details amount of redo data collected by Flashback Database over given time frames.');
  dbms_output.put_line('db_fdb_status                       Provide an overview of the current state of the Flashback Database feature.');
  dbms_output.put_line('db_fk_information                   Displays information on all FKs for the specified schema and table.');
  dbms_output.put_line('db_fra_alerts                       Provide a list of alerts regarding the Oracle Flash Recovery Area.');
  dbms_output.put_line('db_fragmented_tables                This script reports the table that is highly fragmented.');
  dbms_output.put_line('db_fragmented_tables_01             This script lists details how chained or migrated rows there are within a table.');
  dbms_output.put_line('db_full_information                 Script to show full information about the database.');
  dbms_output.put_line('db_gather_table_stats_01            Script to gather statistics for all tables of a specific owner.');
  dbms_output.put_line('db_gather_table_stats_02            Script to gather a specific type of statistics. It could be used to gather TABLE, INDEX, SCHEMA or DATABASE statistics.');
  dbms_output.put_line('db_gather_table_stats_03            This PL/SQL block gathers tables statistics according to the username specified.');
  dbms_output.put_line('db_get_ddl_tables_01                Displays DDL definition for existing users tables.');
  dbms_output.put_line('db_get_ddl_tables_02                Displays DDL definition for existing users tables and indexes.');
  dbms_output.put_line('db_get_ddl_tbs_01                   Displays DDL definitions for existing tablespaces.');
  dbms_output.put_line('db_health_information               Health of Oracle Database. It looks for potential space problems and invalid objects.');
  dbms_output.put_line('db_high_water_mark                  Displays the High Water Mark for the specified table, or all tables.');
  dbms_output.put_line('db_indexes                          Displays Database indexes.');
  dbms_output.put_line('db_index_fragmentation              Displays information abou indexes fragmentation.');
  dbms_output.put_line('db_invalid_indexes                  Displays Database invalid indexes.');
  dbms_output.put_line('db_invalid_objects                  Displays Database invalid objects.');
  dbms_output.put_line('db_invalid_objects_01               Displays Database invalid objects (Owners Not Oracle).');
  dbms_output.put_line('db_io_information                   Displays the amount of IO for each datafile.');
  dbms_output.put_line('db_jobs_running                     Displays information about all jobs currently running.');
  dbms_output.put_line('db_kill_inactive_session            Matar sessoes SNIPED ou INACTIVE ha mais de 3 horas.');
  dbms_output.put_line('db_lob_dump_blob                    This script can be used to dump the contents of a BLOB column ( Read it before ).');
  dbms_output.put_line('db_lob_dump_clob                    This script can be used to dump the contents of a CLOB column ( Read it before ).');
  dbms_output.put_line('db_lob_dump_nclob                   This script can be used to dump the contents of a NCLOB column ( Read it before ).');
  dbms_output.put_line('db_lob_fragmentation_user           Size and amount of fragmentation that exists in all LOB segments for a specific user.');
  dbms_output.put_line('db_locked_objects                   Verificando objetos em lock.');
  dbms_output.put_line('db_locks                            Verifying database locks.');
  dbms_output.put_line('db_locks_01                         Verifying database locks.');
  dbms_output.put_line('db_locks_02                         Verifying database locks.');
  dbms_output.put_line('db_locks_03                         Verifying database locked objects.');
  dbms_output.put_line('db_locks_04                         Verifying database locks.');
  dbms_output.put_line('db_locks_library_cache              Verifying database library cache locks.');
  dbms_output.put_line('db_memory_monitor                   Displays memory allocations for the current database sessions.');
  dbms_output.put_line('db_memory_status                    Instance memory status. This script generates a lst file with memory information.');
  dbms_output.put_line('db_monitor                          Displays SQL statements for the current database sessions.');
  dbms_output.put_line('db_objects                          Show database objects.');
  dbms_output.put_line('db_objects_01                       Show the ten largest objects in the database.');
  dbms_output.put_line('db_objects_02                       Distribution of objects and data. Which schemas are taking up all of the space.');
  dbms_output.put_line('db_objects_being_acessed            Lists all objects being accessed in the schema.');
  dbms_output.put_line('db_objects_being_acessed_01         Lista os objetos sendo acessados por uma determinada sessao.');
  dbms_output.put_line('db_objects_in_library_cache         Displays information about objects in the library cache.');
  dbms_output.put_line('db_parameters                       Displays all instance parameters.');
  dbms_output.put_line('db_partitioned_tables               Shows database partitioned tables by owner ( Not SYS and SYSTEM ).');
  dbms_output.put_line('db_perf_db_block_buffer_usage       Report on the state of all DB_BLOCK_BUFFERS. This script must be run as the SYS user.');
  dbms_output.put_line('db_perf_check_inst_wait_events      Verificacao dos maiores Wait Events das sessões atuais ativas.');
  dbms_output.put_line('db_perf_check_ratio                 Reports all information about Database Ratio.');
  dbms_output.put_line('db_perf_check_session_waits_01      Verifica os Wait Events das sessões atuais.');
  dbms_output.put_line('db_perf_check_session_waits_02      Verifica os Wait Events ociosos (idle).');
  dbms_output.put_line('db_perf_check_session_waits_03      Verifica os Wait Events não ociosos das sessões atuais.');
  dbms_output.put_line('db_perf_check_session_waits_04      Verifica SQL executado por uma sessão.');
  dbms_output.put_line('db_perf_check_session_waits_05_io   Verifica os Wait Events de I/O.');
  dbms_output.put_line('db_perf_check_session_waits_06      Verificar os maiores Wait Events das sessões atuais e os Wait Events de toda a instância.');
  dbms_output.put_line('db_perf_check_session_waits_07      Identifying sessions that are in wait state.');
  dbms_output.put_line('db_perf_check_session_waits_08      Verifying sessions that are in wait state.');
  dbms_output.put_line('db_perf_check_session_waits_vrfy    Identifying sessions in wait state mode.');
  dbms_output.put_line('db_perf_check_sessions_high_io      Script to analyze Disk IO.');
  dbms_output.put_line('db_perf_check_sql_executed          Comando SELECT para verificar SQL executado por uma sessao.');
  dbms_output.put_line('db_perf_check_sql_executed_schema   Quantidade de IO e numero de execucoes das queries por determinado parsing schema e snapshot_id.');
  dbms_output.put_line('db_perf_check_tuning                Displays several performance indicators and comments on the value.');
  dbms_output.put_line('db_perf_file_io                     Reports on Read/Write datafile activity.');
  dbms_output.put_line('db_perf_file_io_efficiency          Gives information based on IO efficiency since the Oracle instance was started.');
  dbms_output.put_line('db_perf_file_waits                  Reports on Busy Buffer Waits per file.');
  dbms_output.put_line('db_perf_hit_ratio_by_session        Reports on all sessions along with their individual hit ratio.');
  dbms_output.put_line('db_perf_objects_without_statistics  Report on all objects that do not have statistics collected on them.');
  dbms_output.put_line('db_perf_read_write_requests         Provide a listing of Read and Writes Requests in the database for the last 30 days.');
  dbms_output.put_line('db_perf_redo_log_contention         Report on overall redolog contention for the instance since it was last started.');
  dbms_output.put_line('db_perf_top_10_tables               Report on top 10 tables with respect to usage and command type.');
  dbms_output.put_line('db_perf_top_sql_by_buffer_gets      Report on top SQL statements ordered by most buffer gets.');
  dbms_output.put_line('db_perf_top_sql_by_disk_reads       Report on top SQL statements ordered by disk reads.');
  dbms_output.put_line('db_pga_advice                       Script to check PGA advices.');
  dbms_output.put_line('db_pga_information                  Script to check how much each session is getting in the PGA.');
  dbms_output.put_line('db_pga_information_01               Consulta estatisticas de consumo de memoria PGA por sessao.');
  dbms_output.put_line('db_profile_ddl                      Displays the DDL for the specified profile(s).');
  dbms_output.put_line('db_query_monitoring                 Select to watch sql execution.');
  dbms_output.put_line('db_rebuild_indexes                  Identificando Indices invalidos e gerando comandos para rebuild.');
  dbms_output.put_line('db_rebuild_partitioned_indexes      Script to rebuild partitioned indexes.');
  dbms_output.put_line('db_redo                             Displays information about database redo logfiles.');
  dbms_output.put_line('db_redo_current_sessions            Script to find redo generated by current sessions.');
  dbms_output.put_line('db_redo_user                        Identify users generating more redo.');
  dbms_output.put_line('db_registry_history                 Displays information about database registry history.');
  dbms_output.put_line('db_registry_information             Displays information about database registry.');
  dbms_output.put_line('db_reorg_index                      Select para selecionar os indices de uma determinada tablespace e mover para outra.');
  dbms_output.put_line('db_reorg_table                      Select para selecionar as tabelas de uma determinada tablespace e mover para outra.');
  dbms_output.put_line('db_resource_active_plan             Lists the currently active resource plan if one is set.');
  dbms_output.put_line('db_resource_consumer_groups         Lists all Resource Manager consumer groups.');
  dbms_output.put_line('db_resource_consumer_group_usage    Lists usage information of consumer groups.');
  dbms_output.put_line('db_resource_limit                   Verica os recursos e limites parametrizados nas instancias.');
  dbms_output.put_line('db_resource_limit_processes         Verica quantidades de processes parametrizados nas instancias e % de utilizacao.');
  dbms_output.put_line('db_resource_plans                   Displays all resource plans from a database.');
  dbms_output.put_line('db_resource_plan_consumer_groups    Lists all consumer groups from a resource manager plan.');
  dbms_output.put_line('db_rollback_information             Displays rollback segment statistics.');
  dbms_output.put_line('db_rollback_segments                Reports rollback statistic information.');
  dbms_output.put_line('db_rollback_segments_statistics     Displays rollback segment statistics.');
  dbms_output.put_line('db_scn_headromm_rate                It checks the database SCN Headroom rate across the time.');
  dbms_output.put_line('db_sec_default_passwords            Checks Oracle created users that still have their default password.');
  dbms_output.put_line('db_sec_users                        Lists all users in the database including their default and temporary tablespaces.');
  dbms_output.put_line('db_sec_roles                        Report on all roles defined in the db and which users are assigned to that role.');
  dbms_output.put_line('db_sessions                         Displays information about database sessions.');
  dbms_output.put_line('db_sessions_active                  Displays information about active database sessions.');
  dbms_output.put_line('db_sessions_inactive                Displays information about inactive database sessions.');
  dbms_output.put_line('db_sessions_usage_history           Displays history information about database sessions and processes consumption.');
  dbms_output.put_line('db_services                         List services registered in the database.');
  dbms_output.put_line('db_sga_free_space                   Reports free memory available in the SGA.');
  dbms_output.put_line('db_sga_information                  Total de memoria, Memoria usada, % de memoria livre da SGA e o total da SGA.');
  dbms_output.put_line('db_sga_information_01               Consultar redimensionamento da SGA, utilizando gerenciamento de memoria automatica.');
  dbms_output.put_line('db_sga_usage_report                 Total de memoria, Memoria usada, % de memoria livre da SGA e o total da SGA.');
  dbms_output.put_line('db_shared_pool_advisor              This script shows if it is necessary to adjust the shared_pool.');
  dbms_output.put_line('db_shared_pool_information          Displays the consumption of shared pool.');
  dbms_output.put_line('db_size                             Database size. Used and allocated.');
  dbms_output.put_line('db_size_by_owner                    Shows database size by owner.');
  dbms_output.put_line('db_sql_executed                     See sql code for Tuning Pack.');
  dbms_output.put_line('db_status                           Displays information about database.');
  dbms_output.put_line('db_stmt_audit_opts                  Show Audited objects in the database.');
  dbms_output.put_line('db_system_parameters                Displays a list of all the system parameters (read it before using).');
  dbms_output.put_line('db_tables_per_datafiles             This script would be useful to findout how tables are spread across different datafiles.');
  dbms_output.put_line('db_tablespace_full                  Displays a list of tablespaces that are nearly full.');
  dbms_output.put_line('db_tablespace_segments              Verificacao de extents de um segmento em uma determinada tablespace.');
  dbms_output.put_line('db_transactions                     Show information about database transactions.');
  dbms_output.put_line('db_transactions_per_day             Shows database transactions volume per day.');
  dbms_output.put_line('db_undo_contention                  Undo contention report.');
  dbms_output.put_line('db_undo_information                 Displays undo information on relevant database sessions.');
  dbms_output.put_line('db_undo_longest_running_query       Find out longest running query in the v$undostat.');
  dbms_output.put_line('db_undo_optimal_info                It shows the optimal undo_retention size to be increased.');
  dbms_output.put_line('db_up_information                   Displays information about database version.');
  dbms_output.put_line('db_used_features.sql                Show all database used features.');
  dbms_output.put_line('db_users                            Displays information about all database users.');
  dbms_output.put_line('db_users_size                       Displays information about all database users with size information.');
  dbms_output.put_line('db_user_operations                  Lista todos os usuarios e o qual a operacao e programa sendo executado no banco.');
  dbms_output.put_line('db_user_operations_01               Displays the user and the text of the statement the user is executing.');
  dbms_output.put_line('db_user_quotas                      Verificando usuarios e quotas no db.');
  dbms_output.put_line('db_version                          Displays information about database version.');
  dbms_output.put_line('dbv                                 Select para selecionar os datafiles do banco de dados ja montando o comando de DBV.');
  dbms_output.put_line('df_usage                            Displays information about datafiles.');
  dbms_output.put_line('df_usage_01                         Checar espacos livres no final dos datafiles para redimensionar a um tamanho menor.');
  dbms_output.put_line('df_usage_02                         Checar espacos livres no final dos datafiles para redimensionar a um tamanho menor.');
  dbms_output.put_line('df_usage_03                         Verificando se um Datafile pode ser redimensionado para um tamanho menor.');
  dbms_output.put_line('db_usage_04                         Displays space usage for each datafile.');
  dbms_output.put_line('df_usage_05                         Verify the water mark in each datafile and check if they could be resized to a smaller size. It mus be run as SYS.');
  dbms_output.put_line('dg_apply_info                       Dataguard log applying information. To be run on the standby database.');
  dbms_output.put_line('dg_arch_destination                 Dataguard archives destination information.');
  dbms_output.put_line('dg_information                      Dataguard general information.');
  dbms_output.put_line('dg_last_messages                    Dataguard status messages.');
  dbms_output.put_line('dg_redo_transport                   Query the physical standby database to monitor Redo Apply and redotransport services activity at the standby site.');
  dbms_output.put_line('exadata_event_operations            This query shows cell events and the operations that caused them.');
  dbms_output.put_line('exadata_list_blocks_physical_read   This query shows the operations that resulted in the cell list of blocks physical read wait event.');
  dbms_output.put_line('exadata_multiblock_physical_read    This query shows the operations that resulted in the cell multiblock physical read wait event.');
  dbms_output.put_line('exadata_single_block_physical_read  This query shows the operations that resulted in the cell single block physical read wait event.');
  dbms_output.put_line('exadata_smart_file_creation         This query shows the operations that resulted in the cell smart file creation wait event.');
  dbms_output.put_line('exadata_smart_incremental_backup    This query shows the operations that resulted in the cell smart incremental backup wait event.');
  dbms_output.put_line('exadata_smart_restore_from_backup   This query shows the operations that resulted in the cell smart restore from backup wait event.');
  dbms_output.put_line('job_status                          Verifying jobs status.');
  dbms_output.put_line('job_status_01                       Verificar SID e Usuarios de JOBS que estao sendo processados na base de dados.');
  dbms_output.put_line('kill_inactive_processes             Matando sessoes inativas no banco de dados.');
  dbms_output.put_line('library_cache_statistics            Verifying database library cache statistcs.');
  dbms_output.put_line('network_acls                        Displays information about network ACLs.');
  dbms_output.put_line('process_active                      Verica os processos que estao ativos no banco de dados.');
  dbms_output.put_line('process_active_01                   Verica os processos que estao ativos no banco de dados com um determinado PID do SO.');
  dbms_output.put_line('process_active_8i                   Verica os processos que estao ativos no banco de dados 8i.');
  dbms_output.put_line('process_detail                      Show Oracle process detail.');
  dbms_output.put_line('process_long_operations             Verica os processos de longa duracao que estao ativos no banco de dados.');
  dbms_output.put_line('process_long_operations_01          Verica os processos de longa duracao que estao ativos no banco de dados.');
  dbms_output.put_line('process_top_20                      Verifica os 20 top process no banco de dados.');
  dbms_output.put_line('process_top_20_01                   Verifica os 20 top process ativos no banco de dados.');
  dbms_output.put_line('process_top_sessions                Verifica as top sessions no banco de dados (WHERE OSUSER <> "oracle").');
  dbms_output.put_line('query_ldapprd                       Lista o inventário de bases do Database Office NET.');
  dbms_output.put_line('rac_information                     Verificacao do status das instancias do RAC.');
  dbms_output.put_line('rac_instances                       Summary report of all configured instances for the current clustered database.');
  dbms_output.put_line('rac_load_balance_status             Verificar balanceamento das instancias em Oracle RAC.');
  dbms_output.put_line('rac_locked_objects                  Displays locked objects for the whole RAC.');
  dbms_output.put_line('rac_locks                           Verifying database locks in a RAC environment.');
  dbms_output.put_line('rac_locks_01                        Verifying database locks in a RAC environment.');
  dbms_output.put_line('rac_long_operations                 Displays information on all long operations for whole RAC.');
  dbms_output.put_line('rac_memory_allocation               Displays memory allocations for the current database sessions for the whole RAC.');
  dbms_output.put_line('rac_monitor_memory                  Displays memory allocations for the current database sessions for the whole RAC.');
  dbms_output.put_line('rac_process_long_operations         Verica os processos de longa duracao que estao ativos no banco de dados em RAC.');
  dbms_output.put_line('rac_session_information             Displays information on all database sessions for whole RAC.');
  dbms_output.put_line('rac_session_undo                    Displays undo information on relevant database sessions.');
  dbms_output.put_line('rac_session_waits                   Displays information on all database session waits for the whole RAC.');
  dbms_output.put_line('rac_sessions                        Displays information on all database sessions for whole RAC.');
  dbms_output.put_line('rac_sessions_active                 Displays information on all active database sessions for whole RAC.');
  dbms_output.put_line('rac_sessions_inactive               Displays information on all inactive database sessions for whole RAC.');
  dbms_output.put_line('rac_up_information                  Displays information about database startup time.');
  dbms_output.put_line('rman_backup_pieces                  Provide a listing of all RMAN Backup Pieces.');
  dbms_output.put_line('rman_bkp_information                Shows information about the database backups executed.');
  dbms_output.put_line('rman_bkp_information_01             Shows information about backup pieces according to the backups informed in the query rman_bkp_information.');
  dbms_output.put_line('rman_bkp_information_02             Shows output log for the backup if OUT AVAILABLE in the query rman_bkp_information is = 1.');
  dbms_output.put_line('rman_bkp_information_03             Exibe o desempenho dos backups feitos via RMAN nos ultimos 30 dias. Dados do Controlfile.');
  dbms_output.put_line('rman_bkp_information_04             Exibe o desempenho dos backups feitos via RMAN nos ultimos 15 dias. Dados do Catalogo.');
  dbms_output.put_line('rman_controlfiles                   Provide a listing of automatically backed up control files.');
  dbms_output.put_line('rman_controlfile_enqueue.sql        Identifying RMAN Controlfile autobackup enqueue locks.');
  dbms_output.put_line('rman_estimated_time                 Estimativa de tempo Backup/Restore Rman.');
  dbms_output.put_line('rman_estimated_time_01              Estimativa de tempo Backup/Restore Rman.');
  dbms_output.put_line('rman_estimated_time_02              Estimativa de tempo Backup/Restore Rman.');
  dbms_output.put_line('rman_estimated_time_9i              Estimativa de tempo Backup/Restore Rman em bases 9i.');
  dbms_output.put_line('rman_netdba_backup_log              Verifica o status dos backups dos bancos de dados da NET.');
  dbms_output.put_line('rman_progress                       Status of rman processes in the database.');
  dbms_output.put_line('rman_progress_01                    Provide a listing of all current RMAN operations and their estimated timings.');
  dbms_output.put_line('rman_rc_databases                   Provide a listing of all databases found in the RMAN recovery catalog.');
  dbms_output.put_line('rman_recovery_datafile_status       Displays the recovery status of each datafile.');
  dbms_output.put_line('rman_sessions                       Simple script for monitoring the RMAN sessions in the db.');
  dbms_output.put_line('rman_sessions_01                    Simple script for monitoring the RMAN sessions in progress in the db.');
  dbms_output.put_line('rman_spfiles                        Provide a listing of automatically backed up spfiles.');
  dbms_output.put_line('rman_throughput                     RMAN channels throughput and % completion.');
  dbms_output.put_line('rman_waits                          RMAN Waits.');
  dbms_output.put_line('select_create_controlfile           Select para criar controlfile para quando o banco está em mount, utilizando somente as V$.');
  dbms_output.put_line('sql_executing_session               Displays information about statements being executed for the sessions.');
  dbms_output.put_line('sql_executing_session_01            Relaciona um processo e o ultimo comando SQL que foi executado.');
  dbms_output.put_line('sql_executing_session_02            Para saber se uma Procedure ou Package esta sendo executada no banco de dados.');
  dbms_output.put_line('sql_executing_session_03            Comandos em execucao nas conexoes ativas.');
  dbms_output.put_line('sql_executing_full_text             Displays all the SQL Text for a session by SQL_ID.');
  dbms_output.put_line('sql_running_parallel                Identifying running with parallel processes.');
  dbms_output.put_line('table_last_analyzed                 Displays tables from a specific schema that are lacking analyzes.');
  dbms_output.put_line('table_locks                         Processos em espera, tipo de lock solicitado e processo segurando a fila de lock.');
  dbms_output.put_line('table_partitions                    Informacoes de tabelas particionadas.');
  dbms_output.put_line('table_skip_corrupted_blocks         Colocando a tabela habilitada para dar skip em blocos corrompidos.');
  dbms_output.put_line('table_statistcs                     Statistics of tables from a schema.');
  dbms_output.put_line('table_usage                         Space used by the tables in the tablespaces (by tablespace).');
  dbms_output.put_line('tables_locked                       It shows information about tables being locked by the sessions.');
  dbms_output.put_line('tbs_estimated_growth_01             This script shows the growth analysis of a specific tablespace in the database.');
  dbms_output.put_line('tbs_estimated_growth_02             This script shows the growth analysis of all tablespaces in the database.');
  dbms_output.put_line('tbs_list_contents                   Displays all the objects for a specific tablespace.');
  dbms_output.put_line('tbs_status                          It shows the status about all database tablespaces.');
  dbms_output.put_line('tbs_temp_session_usage              Sessoes no banco que estao consumindo tablespace temporaria.');
  dbms_output.put_line('tbs_temp_session_usage_01           Sessoes no banco que estao consumindo tablespace temporaria.');
  dbms_output.put_line('tbs_temp_usage                      Verificacao completa de espaco em tablespaces teporarias.');
  dbms_output.put_line('tbs_temp_usage_01                   Verificacao completa de espaco em tablespaces teporarias.');
  dbms_output.put_line('tbs_temp_usage_02                   Verificação de espaço em tablespaces teporárias com autoextend.');
  dbms_output.put_line('tbs_undo_usage                      Verificacao completa de espaco em tablespaces de UNDO.');
  dbms_output.put_line('tbs_undo_usage_01                   Verificacao completa de espaco em tablespaces de UNDO.');
  dbms_output.put_line('tbs_undo_usage_analysis_01          Query to identify optimal undo_retention parameter.');
  dbms_output.put_line('tbs_undo_usage_analysis_02          Query to calculate needed UNDO size for given database activity.');
  dbms_output.put_line('tbs_usage                           Displays information about tablespaces space.');
  dbms_output.put_line('tbs_usage_01                        Verificacao de espaço em tablespaces (nao considera autoextend).');
  dbms_output.put_line('tbs_usage_02                        Verificacao completa de espaco em tablespaces considerando autoextend.');
  dbms_output.put_line('tbs_usage_03                        Displays information about tablespaces that are over 90% used.');
  dbms_output.put_line('tbs_usage_04                        Displays information about tablespaces space with autoextend including temporary tablespaces.');
  dbms_output.put_line('tf_usage                            Displays information about tempfiles.');
  dbms_output.put_line('tf_usage_01                         Displays information about all tempfiles.');
  dbms_output.put_line('user_change_pass                    Montar comandos para alterar senha do usuario.');
  dbms_output.put_line('user_complete_info                  Display better information about user creation in the database with last logon.');
  dbms_output.put_line('user_creation_10g                   Usuario/permissoes. Monta SQL para criacao de outro usuario com os mesmos padroes.');
  dbms_output.put_line('user_creation_11g                   Monta SQL para criacao de outro usuario com os mesmos padroes. Deve ser executado comoSYS.');
  dbms_output.put_line('user_privs                          Mostrar provilegios a um determinado usuario.');
  dbms_output.put_line('user_privs_01                       Displays a list of all roles and priviliges granted to the specified user.');
  dbms_output.put_line('user_privs_02                       Mostrar provilegios a um determinado usuario.');
  dbms_output.put_line('user_privs_03                       Todos os priviegios cadastrados na base de dados.');
  dbms_output.put_line('xplan                               Displays queries explain plans.');
  dbms_output.put_line('========================================================================================================================');
  dbms_output.put(chr(10));
end;
/

prompt

set feed on

--
-- Fim
--
