-- -----------------------------------------------------------------------------------
-- File Name    : db_perf_check_sql_executed_per_schema.sql
-- Description  : Verificando quantidade de IO e execuções de queries por determinado 
--                parsing schema (por snapshot da history)
-- Requirements : Access to the DBA views.
-- Call Syntax  : @db_perf_check_sql_executed_schema.sql
-- Last Modified: 31/08/2017
-- -----------------------------------------------------------------------------------

SET LINES 180
SET PAGES 5000

COL SCHEMA_NAME FORMAT A10
COL INST        FORMAT 9

SELECT SQ.PARSING_SCHEMA_NAME SCHEMA_NAME,
       SQ.INSTANCE_NUMBER INST,
       SQ.SQL_ID, 
       SQ.PLAN_HASH_VALUE, 
	   SUM(DISK_READS_DELTA) DISK_READS, 
	   SUM(DIRECT_WRITES_DELTA) DIRECT_WRITES, 
	   SUM(PHYSICAL_READ_REQUESTS_DELTA) PHYSICAL_READ_REQ, 
       SUM(PHYSICAL_WRITE_REQUESTS_DELTA) PHYSICAL_WRITE_REQ, 
	   SUM(EXECUTIONS_DELTA) EXECUTIONS,
       ROUND(SUM(PHYSICAL_READ_BYTES_DELTA)/1024/1024/1024,2) PHYSICAL_READ_GB, 
	   ROUND(SUM(PHYSICAL_WRITE_BYTES_DELTA)/1024/1024/1024,2) PHYSICAL_WRITE_GB,  
       ROUND((SUM(PHYSICAL_READ_BYTES_DELTA)/1024/1024 + SUM(PHYSICAL_WRITE_BYTES_DELTA)/1024/1024)/180,2) MB_PER_SEC,
       TRUNC(SUM(PHYSICAL_READ_REQUESTS_DELTA + PHYSICAL_WRITE_REQUESTS_DELTA) / 180) IOPS
FROM DBA_HIST_SQLSTAT SQ JOIN DBA_HIST_SQLTEXT S ON (SQ.SQL_ID = S.SQL_ID) JOIN DBA_HIST_SNAPSHOT SN ON (SQ.SNAP_ID = SN.SNAP_ID)
WHERE SQ.PARSING_SCHEMA_NAME = 'CALL_CENTER' AND SQ.SNAP_ID BETWEEN 77766 AND 77773
GROUP BY SQ.PARSING_SCHEMA_NAME, SQ.INSTANCE_NUMBER, SQ.SQL_ID, SQ.PLAN_HASH_VALUE
HAVING ROUND(SUM(PHYSICAL_READ_BYTES_DELTA)/1024/1024/1024,2) > 10
ORDER BY INST, PHYSICAL_READ_GB DESC;
