-- -----------------------------------------------------------------------------------
-- File Name    : db_redo_current_sessions.sql
-- Description  : Script to find redo generated by current sessions
-- Requirements : Access to the DBA views.
-- Call Syntax  : @db_redo_current_sessions.sql
-- Last Modified: 07/07/2016
-- -----------------------------------------------------------------------------------
select v$session.sid, v$session.status, username, round(value/1024/1024,2) as "REDO SIZE MB)"
from v$sesstat, v$statname, v$session
where v$sesstat.STATISTIC# = v$statname.STATISTIC#
  and v$session.sid = v$sesstat.sid
  and name = ‘redo size’
  and value > 0
  and username is not null
order by value desc
/
