-- -----------------------------------------------------------------------------------
-- File Name    : rman_estimated_time.sql
-- Description  : Estimativa de tempo Backup/Restore Rman
-- Requirements : Access to the DBA views.
-- Call Syntax  : @rman_estimated_time.sql
-- Last Modified: 22/10/2012
-- -----------------------------------------------------------------------------------
SET PAGESIZE 10000 LINESIZE 175 COLSEP |
COLUMN SID FORMAT 999999
COLUMN INICIO FORMAT A18
COLUMN STATUS FORMAT A12
COLUMN USUARIO FORMAT A12
COLUMN PREVISAO_TERMINO FORMAT A18
COLUMN OPNAME FORMAT A36
COLUMN TOTAL FORMAT 9999999999
SELECT VS.SID, 
       VS.SERIAL#, 
	   VS.USERNAME USUARIO, 
	   VS.STATUS, 
	   VSL.OPNAME,
       TO_CHAR(START_TIME,'DD/MM/YYYY HH24:MI') INICIO,
       CASE (TOTALWORK*SOFAR) WHEN 0 THEN '' ELSE TO_CHAR(START_TIME+(SYSDATE-START_TIME)/(SOFAR/TOTALWORK),'DD/MM/YYYY HH24:MI') END PREVISAO_TERMINO,
       TOTALWORK TOTAL,
       SOFAR PROCESSADO,
       CASE (TOTALWORK*SOFAR) WHEN 0 THEN 0 ELSE ROUND(SOFAR/TOTALWORK*100,2) END PERC_PROCESSADO
FROM
     GV$SESSION_LONGOPS VSL
JOIN GV$SESSION VS ON VSL.SID = VS.SID AND VS.INST_ID = VSL.INST_ID
WHERE
     TOTALWORK <> SOFAR
 AND VSL.OPNAME LIKE '%RMAN%'
ORDER BY INICIO ASC;


SET LINES 1000 TRIMS ON COLSEP |
COL START_TIME FOR A30
COL OPERATION FOR A15
COL OBJECT_TYPE FOR A20
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YY HH24:MI';
SELECT /*+ RULE */ SID, OPERATION, STATUS, OBJECT_TYPE, START_TIME, SYSDATE, ROUND(MBYTES_PROCESSED, 2) MB_PROCESSED, OUTPUT_DEVICE_TYPE 
FROM V$RMAN_STATUS 
WHERE STATUS LIKE '%RUN%';


SET LINESIZE 126
COLUMN PCT_COMPLETE FORMAT 99.99
COLUMN CLIENT_INFO FORMAT A25
COLUMN SID FORMAT 99999
COLUMN MB_PER_S FORMAT 999.99
SELECT S.CLIENT_INFO,
       L.SID,
       L.SERIAL#,
       L.SOFAR,
       L.TOTALWORK,
       ROUND (L.SOFAR / L.TOTALWORK*100,2) "PCT_COMPLETE",
       AIO.MB_PER_S,
       AIO.LONG_WAIT_PCT
FROM V$SESSION_LONGOPS L,
     V$SESSION S,
    (SELECT SID,
            SERIAL,
            100* SUM (LONG_WAITS) / SUM (IO_COUNT) AS "LONG_WAIT_PCT",
            SUM (EFFECTIVE_BYTES_PER_SECOND)/1024/1024 AS "MB_PER_S"
     FROM V$BACKUP_ASYNC_IO
     GROUP BY SID, SERIAL) AIO
WHERE AIO.SID = S.SID
  AND AIO.SERIAL = S.SERIAL#
  AND L.OPNAME LIKE 'RMAN%'
  AND L.OPNAME NOT LIKE '%aggregate%'
  AND L.TOTALWORK != 0
  AND L.SOFAR <> L.TOTALWORK
  AND S.SID = L.SID
  AND S.SERIAL# = L.SERIAL#
ORDER BY 1;
