-- -----------------------------------------------------------------------------------
-- File Name    : tbs_usage_01.sql
-- Description  : Checking space in tablespaces (does not consider autoextend).
-- Requirements : Access to the DBA views.
-- Call Syntax  : @tbs_usage_01.sql
-- Last Modified: 02/04/2012
-- -----------------------------------------------------------------------------------

PROMPT
PROMPT DISPLAYS INFORMATION (DESCENDING) ABOUT TABLESPACES SPACE CONSUMPTION (NOT CONSIDERING DATAFILES IN AUTOEXTEND MODE)
PROMPT

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';

SET LINES 180 PAGES 5000 COLSEP |

COL   "NAME"       FORMAT A22
COL   "SIZE (M)"   FORMAT A15
COL   "USED (M)"   FORMAT A15
COL   "USED %"     FORMAT A6

SELECT D.TABLESPACE_NAME "NAME",
       D.STATUS "STATUS",
       D.CONTENTS "TYPE",
       D.EXTENT_MANAGEMENT "EXTENT MANAGEMENT",
       RTRIM(LTRIM(TO_CHAR(NVL(A.BYTES / 1024 / 1024, 0),'99,999,990.90'))) "SIZE (M)",
       RTRIM(LTRIM(TO_CHAR(NVL(A.BYTES - NVL(F.BYTES, 0), 0)/1024/1024,'99,999,990.90'))) "USED (M)",
       RTRIM(LTRIM(TO_CHAR(NVL((A.BYTES - NVL(F.BYTES, 0)) / A.BYTES * 100, 0), '990.00'))) "USED %",
       DECODE(GREATEST(NVL((A.BYTES - NVL(F.BYTES, 0)) / A.BYTES * 100, 0),95),
       		       95,
       		       '   OK    ',
       		       ' [ALERTA] '
    	      ) ALERTS
FROM SYS.DBA_TABLESPACES D,
     (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES
      FROM   DBA_DATA_FILES
      GROUP BY TABLESPACE_NAME) A,
     (SELECT TABLESPACE_NAME,
      SUM(BYTES) BYTES
      FROM DBA_FREE_SPACE
      GROUP BY TABLESPACE_NAME) F
WHERE D.TABLESPACE_NAME = A.TABLESPACE_NAME(+)
  AND D.TABLESPACE_NAME = F.TABLESPACE_NAME(+)
  AND NOT (D.EXTENT_MANAGEMENT LIKE 'LOCAL' AND D.CONTENTS LIKE 'TEMPORARY')
UNION ALL
SELECT D.TABLESPACE_NAME "NAME",
       D.STATUS "STATUS",
       D.CONTENTS "TYPE",
       D.EXTENT_MANAGEMENT "EXTENT MANAGEMENT",
       RTRIM(LTRIM(TO_CHAR(NVL(A.BYTES / 1024 / 1024, 0),'99,999,990.90'))) "SIZE (M)",
       RTRIM(LTRIM(TO_CHAR(NVL(T.BYTES, 0)/1024/1024,'99,999,990.90'))) "USED (M)",
       RTRIM(LTRIM(TO_CHAR(NVL(T.BYTES / A.BYTES * 100, 0), '990.00'))) "USED %",
       DECODE(GREATEST(NVL(T.BYTES / A.BYTES * 100, 0),98),
       		       98,
       		       '   OK    ',
       		       ' [ALERTA] '
    	      ) ALERTS
FROM SYS.DBA_TABLESPACES D,
     (SELECT TABLESPACE_NAME,
             SUM(BYTES) BYTES
      FROM   DBA_TEMP_FILES
      GROUP BY TABLESPACE_NAME) A,
     (SELECT TABLESPACE_NAME,
             SUM(BYTES_CACHED) BYTES
      FROM   V$TEMP_EXTENT_POOL
      GROUP BY TABLESPACE_NAME) T
WHERE  D.TABLESPACE_NAME = A.TABLESPACE_NAME(+)
  AND  D.TABLESPACE_NAME = T.TABLESPACE_NAME(+)
  AND  D.EXTENT_MANAGEMENT LIKE 'LOCAL'
  AND  D.CONTENTS LIKE 'TEMPORARY'
ORDER BY 7 DESC
/
